- name: Configure project # <-- Словесное описание сценария(name)
  hosts: application # <-- Для каких хостов будут выполняться описанные ниже таски (hosts)
  become: true

  roles:
    - project_roles
    - { role: riemers.gitlab-runner } 
    -  { role: geerlingguy.docker }



