---
# tasks file for project_roles
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Install gitlab-cli
      apt:
        name: gitlab-cli
        state: present    

    - name: Install git
      apt:
        name: git
        state: present
        update_cache: yes        
    
    





